# mkdocs.yml for xInfer

site_name: xInfer Performance Toolkit
site_url: https://your-username.github.io/xinfer/  # Replace with your actual URL
repo_url: https://github.com/your-username/xinfer   # Replace with your repo URL
repo_name: your-username/xinfer

theme:
  name: material
  logo: assets/xinfer_logo.png # Add your logo
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

# The navigation sidebar structure, designed for a standalone xInfer project
nav:
  - Home: index.md
  - Installation: installation.md
  - 🚀 Quickstart: quickstart.md
  - Concepts:
      - Philosophy: concepts/philosophy.md
      - The xInfer Workflow: concepts/workflow.md
  - How-to Guides:
      - Building TensorRT Engines: guides/building-engines.md
      - INT8 Quantization: guides/int8-quantization.md
      - Building Custom Pipelines: guides/custom-pipelines.md
  - The Model Zoo API:
      - Overview: zoo-api/index.md
      - Computer Vision: zoo-api/vision.md
      - Generative AI: zoo-api/generative.md
      - Natural Language Processing: zoo-api/nlp.md
      - Audio & DSP: zoo-api/audio.md
      - Time Series: zoo-api/timeseries.md
      - 3D & Spatial: zoo-api/threed.md
      - Geospatial: zoo-api/geospatial.md
      - Medical: zoo-api/medical.md
      - Document AI: zoo-api/document.md
      - Specialized Models: zoo-api/special.md
  - Core Toolkit API Reference:
      - Overview: core-api/index.md
      - Core Runtime: core-api/engine.md
      - Engine Builders: core-api/builders.md
      - Pre-processing: core-api/preproc.md
      - Post-processing: core-api/postproc.md
  - Ignition Hub (Cloud):
      - Introduction: hub/index.md
      - Usage Guide: hub/usage.md

# For syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition