#include "mainwindow.h"
#include "./ui_mainwindow.h" // Generated by CMake
#include <QFileDialog>
#include <QMessageBox>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    // Setup Threading
    m_workerThread = new QThread(this);
    m_controller = new ZooController();
    m_controller->moveToThread(m_workerThread);

    // Connect Signals
    connect(m_controller, &ZooController::frameReady, this, &MainWindow::updateView);
    connect(m_controller, &ZooController::errorOccurred, this, &MainWindow::handleError);

    // Start thread event loop
    m_workerThread->start();
}

MainWindow::~MainWindow() {
    m_controller->stopPipeline();
    m_workerThread->quit();
    m_workerThread->wait();
    delete m_controller;
    delete ui;
}

void MainWindow::on_btnStart_clicked() {
    // Get inputs from UI
    QString modelFile = ui->lineEditModel->text();
    if (modelFile.isEmpty()) {
        QMessageBox::warning(this, "Error", "Please select a model file.");
        return;
    }

    // Trigger start in background thread
    // Note: We use QMetaObject::invokeMethod to ensure thread safety if needed,
    // or rely on signals if we defined a signal startRequested(path, id)
    QMetaObject::invokeMethod(m_controller, "startPipeline",
                              Q_ARG(std::string, modelFile.toStdString()),
                              Q_ARG(int, 0)); // Camera 0
}

void MainWindow::on_btnStop_clicked() {
    QMetaObject::invokeMethod(m_controller, "stopPipeline");
}

void MainWindow::updateView(const QImage& image) {
    ui->videoWidget->updateFrame(image); // Our custom widget
}

void MainWindow::handleError(QString msg) {
    QMessageBox::critical(this, "xInfer Error", msg);
}