#pragma once

#include <string>
#include <vector>
#include "types.h"

namespace xinfer::backends::qnn {

/**
 * @brief Configuration for Qualcomm QNN Backend
 */
struct QnnConfig {
    // Path to the serialized Context Binary (.bin / .so)
    // Generated by qnn-context-binary-generator
    std::string model_path;

    // Target Hardware
    QnnBackendType backend_type = QnnBackendType::HTP;

    // Performance Voting
    HtpPerformanceMode performance_mode = HtpPerformanceMode::SUSTAINED_HIGH;

    // --- Library Paths (Crucial for QNN) ---
    // QNN requires dynamically loading backend libraries (.so/.dll).
    // If empty, xInfer attempts to find them in LD_LIBRARY_PATH or QNN_SDK_ROOT.
    
    // e.g. "/opt/qcom/qnn/lib/libQnnHtp.so"
    std::string qnn_backend_lib_path;
    
    // e.g. "/opt/qcom/qnn/lib/libQnnSystem.so"
    std::string qnn_system_lib_path;

    // Enable internal profiling?
    bool enable_profiling = false;

    // Path to save cached binary (if compiling from source graph, unlikely in runtime)
    std::string cached_binary_path;
};

} // namespace xinfer::backends::qnn