#pragma once

#include <string>
#include <vector>
#include <cstdint>
#include "types.h"

namespace xinfer::backends::exynos {

/**
 * @brief Configuration for Samsung Exynos Backend
 */
struct ExynosConfig {
    // Path to the compiled model binary (.nnc / .sg / .bin)
    // Generated by the ENN Compiler (enn_converter).
    std::string model_path;

    // Performance / Power Settings
    EnnPowerMode power_mode = EnnPowerMode::DEFAULT;
    EnnPriority priority = EnnPriority::NORMAL;

    // Optimization: Pre-allocate IO buffers in ION memory?
    bool use_ion_buffers = true;

    // If true, enables the 'Fast-RPC' path if available (lower latency)
    bool enable_fast_rpc = false;

    // Target specific NPU core ID (0 = Auto, 1 = NPU0, 2 = NPU1/DSP)
    int core_affinity = 0;
};

} // namespace xinfer::backends::exynos